/**
 * Generates fake tryout data for development. Prints SQL to stdout.
 *
 *   npm run seed:dev > /tmp/seed-dev.sql
 *
 * Positions and attributes are READ FROM lib/config/positions.ts, never
 * written out here - CLAUDE.md rule 2. That is the whole reason this is a
 * generator rather than a hand-written .sql file.
 *
 * The generated SQL resolves the tryout and officer by lookup, so no UUIDs
 * are baked into anything committed.
 *
 * Deliberately produces a mix of states so the gating rule in SPEC.md
 * section 8 is actually exercised:
 *   - fully rated prospects that should show a number
 *   - partially rated ones that must show progress instead
 *   - unrated ones
 *   - more than MIN_TIMED_FOR_PERCENTILE prospects with a 40 time, so the
 *     speed percentile becomes valid
 */

import {
  BOARD_ORDER,
  POSITIONS,
  MAX_FORTY_ATTEMPTS,
  type PositionKey,
} from "../lib/config/positions";

// Deterministic PRNG so reruns produce identical data.
let seed = 20250913;
function rand() {
  seed = (seed * 1664525 + 1013904223) % 4294967296;
  return seed / 4294967296;
}
function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(rand() * arr.length)];
}
function between(lo: number, hi: number) {
  return lo + rand() * (hi - lo);
}

const FIRST = [
  "Marcus", "DeShawn", "Jordan", "Tyler", "Amir", "Connor", "Darius", "Malik",
  "Devon", "Isaiah", "Xavier", "Elijah", "Cameron", "Trevor", "Andre", "Jaylen",
  "Brandon", "Micah", "Terrell", "Nolan", "Rashad", "Gavin", "Omar", "Kendrick",
  "Lucas", "Bryce", "Damian", "Ethan", "Julian", "Kai", "Marquis", "Preston",
  "Quentin", "Roman", "Silas", "Tobias", "Vince", "Wesley", "Zane", "Colton",
];
const LAST = [
  "Reid", "Carter", "Hayes", "Brooks", "Jackson", "Walsh", "Thompson", "Green",
  "Price", "Forte", "Ellis", "Bryant", "Nash", "Coleman", "Whitfield", "Barnes",
  "Doyle", "Sutton", "Vaughn", "Mercer", "Lang", "Okafor", "Ramirez", "Boyd",
  "Sinclair", "Ortega", "Reyes", "Sharpe", "Ingram", "Dalton", "Frazier", "Cole",
  "Hollis", "Marsh", "Padilla", "Quinn", "Rowe", "Tate", "Underwood", "Vance",
];

const POSITION_KEYS = Object.keys(POSITIONS) as PositionKey[];

// Roughly how a flag football tryout actually skews, indexed against
// BOARD_ORDER rather than naming positions - add a position to the config and
// it gets seeded automatically at the default count instead of being silently
// skipped. CLAUDE.md rule 2.
const COUNT_BY_BOARD_INDEX = [4, 6, 10, 8, 6, 6];
const DEFAULT_COUNT = 6;
const DISTRIBUTION: PositionKey[] = BOARD_ORDER.flatMap((p, i) =>
  Array<PositionKey>(COUNT_BY_BOARD_INDEX[i] ?? DEFAULT_COUNT).fill(p),
);

const TOTAL = DISTRIBUTION.length;
const WITH_FORTY = 24;      // > MIN_TIMED_FOR_PERCENTILE (15), so percentiles turn on
const FULLY_RATED = 22;     // should display a rating
const PARTIALLY_RATED = 9;  // should display progress instead
// remainder gets nothing

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const lines: string[] = [];
lines.push("-- GENERATED by scripts/seed-dev.ts - do not edit, do not commit.");
lines.push("-- Fake development data. Safe to re-run; it clears prospects first.");
lines.push("begin;");
lines.push("");
lines.push("-- Dev reset. Cascades to ratings, drill_results, selections, comments.");
lines.push(
  "delete from prospects where tryout_id = (select id from tryouts where is_active order by created_at limit 1);",
);
lines.push("");

// ---- prospects ----------------------------------------------------------
const jerseys = new Set<number>();
type P = { jersey: number; first: string; last: string; pos: PositionKey; secondary: PositionKey[] };
const prospects: P[] = [];

for (let i = 0; i < TOTAL; i++) {
  let jersey = 0;
  do {
    jersey = 1 + Math.floor(rand() * 98);
  } while (jerseys.has(jersey));
  jerseys.add(jersey);

  const pos = DISTRIBUTION[i];
  // About a third try out at a second position.
  const secondary: PositionKey[] = [];
  if (rand() < 0.35) {
    const other = pick(POSITION_KEYS.filter((p) => p !== pos));
    secondary.push(other);
  }

  prospects.push({
    jersey,
    first: pick(FIRST),
    last: pick(LAST),
    pos,
    secondary,
  });
}

lines.push("insert into prospects");
lines.push(
  "  (tryout_id, jersey_number, first_name, last_name, primary_position, secondary_positions)",
);
lines.push("select t.id, v.jersey, v.first, v.last, v.pos, v.sec::text[]");
lines.push("from (select id from tryouts where is_active order by created_at limit 1) t,");
lines.push("(values");
lines.push(
  prospects
    .map(
      (p) =>
        `  (${p.jersey}, ${q(p.first)}, ${q(p.last)}, ${q(p.pos)}, ` +
        `${q(`{${p.secondary.join(",")}}`)})`,
    )
    .join(",\n"),
);
lines.push(") as v(jersey, first, last, pos, sec);");
lines.push("");

// ---- 40 yard dash -------------------------------------------------------
lines.push("-- 40 times. Enough prospects timed to make the percentile valid.");
const timed = prospects.slice(0, WITH_FORTY);
const drillRows: string[] = [];
for (const p of timed) {
  const attempts = rand() < 0.5 ? MAX_FORTY_ATTEMPTS : 1;
  // OL run slower; skill positions faster.
  const base = p.pos === "OL" ? between(5.1, 5.9) : between(4.35, 5.25);
  for (let a = 1; a <= attempts; a++) {
    const v = (base + (a === 1 ? 0 : between(-0.06, 0.14))).toFixed(2);
    drillRows.push(`  (${p.jersey}, ${a}, ${v})`);
  }
}
lines.push(
  "insert into drill_results (prospect_id, drill_key, attempt_number, value, recorded_by)",
);
lines.push("select p.id, 'forty', v.attempt, v.val, o.id");
lines.push("from (values");
lines.push(drillRows.join(",\n"));
lines.push(") as v(jersey, attempt, val)");
lines.push("join prospects p on p.jersey_number = v.jersey");
lines.push("  and p.tryout_id = (select id from tryouts where is_active order by created_at limit 1)");
lines.push("cross join (select id from officers order by created_at limit 1) o;");
lines.push("");

// ---- ratings ------------------------------------------------------------
lines.push("-- Ratings from the seeded officer. Attribute keys come from");
lines.push("-- lib/config/positions.ts via the generator, never hardcoded.");
const ratingRows: string[] = [];
prospects.forEach((p, i) => {
  const full = i < FULLY_RATED;
  const partial = !full && i < FULLY_RATED + PARTIALLY_RATED;
  if (!full && !partial) return;

  // Union of attributes across all positions this prospect plays.
  const attrs = new Set<string>();
  for (const pos of [p.pos, ...p.secondary]) {
    for (const a of POSITIONS[pos].attributes) attrs.add(a);
  }
  let list = [...attrs];
  // Partial prospects are missing one required attribute, so the gate fires.
  if (partial) list = list.slice(0, Math.max(1, list.length - 1));

  for (const a of list) {
    const v = (Math.round(between(3, 10) * 10) / 10).toFixed(1);
    ratingRows.push(`  (${p.jersey}, ${q(a)}, ${v})`);
  }
});
lines.push("insert into ratings (prospect_id, officer_id, attribute_key, value)");
lines.push("select p.id, o.id, v.attr, v.val");
lines.push("from (values");
lines.push(ratingRows.join(",\n"));
lines.push(") as v(jersey, attr, val)");
lines.push("join prospects p on p.jersey_number = v.jersey");
lines.push("  and p.tryout_id = (select id from tryouts where is_active order by created_at limit 1)");
lines.push("cross join (select id from officers order by created_at limit 1) o;");
lines.push("");
lines.push("commit;");

console.log(lines.join("\n"));

console.error(
  `-- generated ${TOTAL} prospects, ${drillRows.length} drill rows, ` +
    `${ratingRows.length} ratings (${FULLY_RATED} full, ${PARTIALLY_RATED} partial, ` +
    `${TOTAL - FULLY_RATED - PARTIALLY_RATED} unrated, ${WITH_FORTY} timed)`,
);
